// AUTO-GENERATED by scripts/generate_publications.mjs from data/publications.bib
// Do not edit by hand. Run `npm run pubs` after editing the .bib file.

export type PublicationKind = "conference" | "journal";

export type Publication = {
  id: string;            // BibTeX citation key
  title: string;
  authors: string[];     // "First Last" order, as listed on the paper
  venue: string;         // full venue name
  venueShort: string;    // acronym, e.g. "INFOCOM", "TVT"
  venueTag: string;      // acronym + 2-digit year, e.g. "INFOCOM '26"
  year: number;
  kind: PublicationKind;
  keywords: string[];    // 2-3 research keywords
  award?: string;        // e.g. "Best Paper Award"
};

export type ResearchArea = {
  id: string;            // "wireless" | "embodied" | "cps" | "other"
  title: string;
  description: string;   // one-sentence summary of the research direction
  items: Publication[];  // newest first
};

export const researchAreas: ResearchArea[] = [
  {
    "id": "wireless",
    "title": "Wireless Networks",
    "description": "Trustworthy AI-based network control for open and programmable mobile networks, including O-RAN automation, network slicing, continual adaptation under network dynamics, and end-to-end resource orchestration.",
    "items": [
      {
        "id": "zhao2026inran",
        "title": "inRAN: Interpretable Online Bayesian Learning for Network Automation in Open Radio Access Networks",
        "authors": [
          "Ming Zhao",
          "Yuru Zhang",
          "Qiang Liu",
          "Ahan Kak",
          "Nakjung Choi"
        ],
        "venue": "IEEE Conference on Computer Communications (INFOCOM)",
        "venueShort": "INFOCOM",
        "venueTag": "INFOCOM '26",
        "year": 2026,
        "kind": "conference",
        "keywords": [
          "O-RAN",
          "Network Automation",
          "Interpretable AI"
        ]
      },
      {
        "id": "zhao2025adaslicing",
        "title": "AdaSlicing: Adaptive Online Network Slicing Under Continual Network Dynamics in Open Radio Access Networks",
        "authors": [
          "Ming Zhao",
          "Yuru Zhang",
          "Qiang Liu",
          "Ahan Kak",
          "Nakjung Choi"
        ],
        "venue": "IEEE Conference on Computer Communications (INFOCOM)",
        "venueShort": "INFOCOM",
        "venueTag": "INFOCOM '25",
        "year": 2025,
        "kind": "conference",
        "keywords": [
          "Network Slicing",
          "Continual Adaptation",
          "Online Learning"
        ]
      },
      {
        "id": "hu2024information",
        "title": "Information Bottleneck-Based Domain Adaptation for Hybrid Deep Learning in Scalable Network Slicing",
        "authors": [
          "Tianlun Hu",
          "Qi Liao",
          "Qiang Liu",
          "Georg Carle"
        ],
        "venue": "IEEE Transactions on Machine Learning in Communications and Networking",
        "venueShort": "TMLCN",
        "venueTag": "TMLCN '24",
        "year": 2024,
        "kind": "journal",
        "keywords": [
          "Network Slicing",
          "Domain Adaptation",
          "Hybrid Deep Learning"
        ]
      },
      {
        "id": "hu2023fast",
        "title": "Fast and Scalable Network Slicing by Integrating Deep Learning with Lagrangian Methods",
        "authors": [
          "Tianlun Hu",
          "Qi Liao",
          "Qiang Liu",
          "Antonio Massaro",
          "Georg Carle"
        ],
        "venue": "IEEE Global Communications Conference (GLOBECOM)",
        "venueShort": "GLOBECOM",
        "venueTag": "GLOBECOM '23",
        "year": 2023,
        "kind": "conference",
        "keywords": [
          "Network Slicing",
          "Deep Learning",
          "Lagrangian Methods"
        ]
      },
      {
        "id": "zhang2023ronet",
        "title": "RoNet: Toward Robust Neural Assisted Mobile Network Configuration",
        "authors": [
          "Yuru Zhang",
          "Yongjie Xue",
          "Qiang Liu",
          "Nakjung Choi",
          "Tao Han"
        ],
        "venue": "IEEE International Conference on Communications (ICC)",
        "venueShort": "ICC",
        "venueTag": "ICC '23",
        "year": 2023,
        "kind": "conference",
        "keywords": [
          "Network Configuration",
          "Robust Learning",
          "Neural-Assisted Control"
        ]
      },
      {
        "id": "hu2023inter",
        "title": "Inter-Cell Network Slicing with Transfer Learning Empowered Multi-Agent Deep Reinforcement Learning",
        "authors": [
          "Tianlun Hu",
          "Qi Liao",
          "Qiang Liu",
          "Georg Carle"
        ],
        "venue": "IEEE Open Journal of the Communications Society",
        "venueShort": "OJ-COMS",
        "venueTag": "OJ-COMS '23",
        "year": 2023,
        "kind": "journal",
        "keywords": [
          "Network Slicing",
          "Transfer Learning",
          "Multi-Agent RL"
        ]
      },
      {
        "id": "liu2022deep",
        "title": "Deep Reinforcement Learning for End-to-End Network Slicing: Challenges and Solutions",
        "authors": [
          "Qiang Liu",
          "Nakjung Choi",
          "Tao Han"
        ],
        "venue": "IEEE Network Magazine",
        "venueShort": "IEEE Network",
        "venueTag": "IEEE Network '22",
        "year": 2022,
        "kind": "journal",
        "keywords": [
          "Network Slicing",
          "Deep RL",
          "End-to-End"
        ]
      },
      {
        "id": "liu2022atlas",
        "title": "Atlas: Automate Online Service Configuration in Network Slicing",
        "authors": [
          "Qiang Liu",
          "Nakjung Choi",
          "Tao Han"
        ],
        "venue": "Proceedings of the 18th International Conference on emerging Networking EXperiments and Technologies (CoNEXT)",
        "venueShort": "CoNEXT",
        "venueTag": "CoNEXT '22",
        "year": 2022,
        "kind": "conference",
        "keywords": [
          "Network Slicing",
          "Service Configuration",
          "Online Learning"
        ]
      },
      {
        "id": "hu2022network",
        "title": "Network Slicing via Transfer Learning aided Distributed Deep Reinforcement Learning",
        "authors": [
          "Tianlun Hu",
          "Qi Liao",
          "Qiang Liu",
          "Georg Carle"
        ],
        "venue": "IEEE Global Communications Conference (GLOBECOM)",
        "venueShort": "GLOBECOM",
        "venueTag": "GLOBECOM '22",
        "year": 2022,
        "kind": "conference",
        "keywords": [
          "Network Slicing",
          "Transfer Learning",
          "Distributed RL"
        ]
      },
      {
        "id": "hu2022inter",
        "title": "Inter-cell Slicing Resource Partitioning via Coordinated Multi-Agent Deep Reinforcement Learning",
        "authors": [
          "Tianlun Hu",
          "Qi Liao",
          "Qiang Liu",
          "Dan Wellington",
          "Georg Carle"
        ],
        "venue": "IEEE International Conference on Communications (ICC)",
        "venueShort": "ICC",
        "venueTag": "ICC '22",
        "year": 2022,
        "kind": "conference",
        "keywords": [
          "Network Slicing",
          "Multi-Agent RL",
          "Resource Partitioning"
        ],
        "award": "Best Paper Award"
      },
      {
        "id": "liu2021onslicing",
        "title": "OnSlicing: Online End-to-End Network Slicing with Reinforcement Learning",
        "authors": [
          "Qiang Liu",
          "Nakjung Choi",
          "Tao Han"
        ],
        "venue": "Proceedings of the 17th International Conference on emerging Networking EXperiments and Technologies (CoNEXT)",
        "venueShort": "CoNEXT",
        "venueTag": "CoNEXT '21",
        "year": 2021,
        "kind": "conference",
        "keywords": [
          "Network Slicing",
          "Reinforcement Learning",
          "Safe Online Learning"
        ]
      },
      {
        "id": "liu2021constraint",
        "title": "Constraint-Aware Deep Reinforcement Learning for End-to-End Resource Orchestration in Mobile Networks",
        "authors": [
          "Qiang Liu",
          "Nakjung Choi",
          "Tao Han"
        ],
        "venue": "IEEE 29th International Conference on Network Protocols (ICNP)",
        "venueShort": "ICNP",
        "venueTag": "ICNP '21",
        "year": 2021,
        "kind": "conference",
        "keywords": [
          "Resource Orchestration",
          "Constrained RL",
          "End-to-End Networks"
        ]
      }
    ]
  },
  {
    "id": "embodied",
    "title": "Embodied Intelligence",
    "description": "Connecting autonomous agents so they perceive and compute together, through cooperative perception, edge intelligence, collaborative vehicle-edge computing, and distributed inference.",
    "items": [
      {
        "id": "cao2026edgeserving",
        "title": "EdgeServing: Deadline-Aware Multi-DNN Serving at the Edge",
        "authors": [
          "Jiahe Cao",
          "Xiaomeng Li",
          "Qiang Liu",
          "Tao Han",
          "Ning Zhang",
          "Weisong Shi"
        ],
        "venue": "2026 35th International Conference on Computer Communications and Networks (ICCCN)",
        "venueShort": "ICCCN",
        "venueTag": "ICCCN '26",
        "year": 2026,
        "kind": "conference",
        "keywords": [
          "Edge AI",
          "Multi-DNN Serving",
          "Deadline-Aware Scheduling"
        ]
      },
      {
        "id": "zhao2024lefi",
        "title": "LeFi: Learn to Incentivize Federated Learning in Automotive Edge Computing",
        "authors": [
          "Ming Zhao",
          "Yuru Zhang",
          "Qiang Liu",
          "Tao Han"
        ],
        "venue": "IEEE Global Communications Conference (GLOBECOM)",
        "venueShort": "GLOBECOM",
        "venueTag": "GLOBECOM '24",
        "year": 2024,
        "kind": "conference",
        "keywords": [
          "Federated Learning",
          "Incentive Design",
          "Automotive Edge"
        ]
      },
      {
        "id": "cao2024cave",
        "title": "CAVE: Crowdsourcing Passing-By Vehicles for Reliable In-Vehicle Edge Computing",
        "authors": [
          "Jiahe Cao",
          "Qiang Liu",
          "Dawei Chen",
          "Kyungtae Han"
        ],
        "venue": "IEEE Global Communications Conference (GLOBECOM)",
        "venueShort": "GLOBECOM",
        "venueTag": "GLOBECOM '24",
        "year": 2024,
        "kind": "conference",
        "keywords": [
          "Vehicular Edge Computing",
          "Crowdsourcing",
          "Reliability"
        ]
      },
      {
        "id": "zhang2024crowdsourcing",
        "title": "Crowdsourcing Live High Definition Map via Collaborative Computation in Automotive Edge Computing",
        "authors": [
          "Yuru Zhang",
          "Qiang Liu",
          "Haoxin Wang",
          "Dawei Chen",
          "Kyungtae Han"
        ],
        "venue": "IEEE Transactions on Vehicular Technology",
        "venueShort": "TVT",
        "venueTag": "TVT '24",
        "year": 2024,
        "kind": "journal",
        "keywords": [
          "HD Map",
          "Collaborative Computing",
          "Automotive Edge"
        ]
      },
      {
        "id": "liu2023adamap",
        "title": "AdaMap: High-Scalable Real-Time Cooperative Perception at the Edge",
        "authors": [
          "Qiang Liu",
          "Yongjie Xue",
          "Yuru Zhang",
          "Dawei Chen",
          "Kyungtae Han"
        ],
        "venue": "IEEE/ACM Symposium on Edge Computing (SEC)",
        "venueShort": "SEC",
        "venueTag": "SEC '23",
        "year": 2023,
        "kind": "conference",
        "keywords": [
          "Cooperative Perception",
          "Edge AI",
          "Resource Orchestration"
        ]
      },
      {
        "id": "xue2023comap",
        "title": "CoMap: Proactive Provision for Crowdsourcing Map in Automotive Edge Computing",
        "authors": [
          "Yongjie Xue",
          "Yuru Zhang",
          "Qiang Liu",
          "Dawei Chen",
          "Kyungtae Han"
        ],
        "venue": "IEEE International Conference on Communications (ICC)",
        "venueShort": "ICC",
        "venueTag": "ICC '23",
        "year": 2023,
        "kind": "conference",
        "keywords": [
          "Crowdsourcing Map",
          "Proactive Provisioning",
          "Automotive Edge"
        ]
      },
      {
        "id": "liu2022real",
        "title": "Real-Time Dynamic Map with Crowdsourcing Vehicles in Edge Computing",
        "authors": [
          "Qiang Liu",
          "Tao Han",
          "Jiang Linda Xie",
          "BaekGyu Kim"
        ],
        "venue": "IEEE Transactions on Intelligent Vehicles",
        "venueShort": "TIV",
        "venueTag": "TIV '22",
        "year": 2022,
        "kind": "journal",
        "keywords": [
          "Dynamic Map",
          "Crowdsourcing Vehicles",
          "Edge Computing"
        ]
      },
      {
        "id": "liu2022edgemap",
        "title": "EdgeMap: CrowdSourcing High Definition Map in Automotive Edge Computing",
        "authors": [
          "Qiang Liu",
          "Yuru Zhang",
          "Haoxin Wang"
        ],
        "venue": "IEEE International Conference on Communications (ICC)",
        "venueShort": "ICC",
        "venueTag": "ICC '22",
        "year": 2022,
        "kind": "conference",
        "keywords": [
          "HD Map",
          "Crowdsourcing",
          "Automotive Edge"
        ]
      },
      {
        "id": "liu2021livemap",
        "title": "LiveMap: Real-Time Dynamic Map in Automotive Edge Computing",
        "authors": [
          "Qiang Liu",
          "Tao Han",
          "Jiang Linda Xie",
          "BaekGyu Kim"
        ],
        "venue": "IEEE Conference on Computer Communications (INFOCOM)",
        "venueShort": "INFOCOM",
        "venueTag": "INFOCOM '21",
        "year": 2021,
        "kind": "conference",
        "keywords": [
          "Dynamic Map",
          "Real-Time Perception",
          "Automotive Edge"
        ]
      }
    ]
  },
  {
    "id": "cps",
    "title": "Cyber-Physical Systems",
    "description": "Closing the loop between the physical and digital worlds with wireless digital twins, physical-AI integration, and predictive decision-making grounded in real-world measurements.",
    "items": [
      {
        "id": "zhang2026radtwin",
        "title": "RadTwin: Generalizable Wireless Digital Twin for Dynamic Environments",
        "authors": [
          "Yuru Zhang",
          "Ming Zhao",
          "Qiang Liu",
          "Ahmed Alkhateeb",
          "Abhishek K. Agrawal",
          "Qi Qu"
        ],
        "venue": "2026 35th International Conference on Computer Communications and Networks (ICCCN)",
        "venueShort": "ICCCN",
        "venueTag": "ICCCN '26",
        "year": 2026,
        "kind": "conference",
        "keywords": [
          "Wireless Digital Twin",
          "Generalization",
          "Dynamic Environments"
        ],
        "award": "Best Paper Award"
      },
      {
        "id": "li2026automatic",
        "title": "Automatic Network Planning with Digital Radio Twin",
        "authors": [
          "Xiaomeng Li",
          "Yuru Zhang",
          "Qiang Liu",
          "Mehmet Can Vuran",
          "Nathan Huynh",
          "Li Zhao",
          "Mizan Rahman",
          "Eren Erman Ozguven"
        ],
        "venue": "IEEE International Conference on Communications (ICC)",
        "venueShort": "ICC",
        "venueTag": "ICC '26",
        "year": 2026,
        "kind": "conference",
        "keywords": [
          "Digital Radio Twin",
          "Network Planning",
          "Sim-to-Real"
        ]
      },
      {
        "id": "zhang2026onetwin",
        "title": "oneTwin: Online Digital Network Twin via Neural Radio Radiance Field",
        "authors": [
          "Yuru Zhang",
          "Ming Zhao",
          "Qiang Liu",
          "Nakjung Choi"
        ],
        "venue": "IEEE Conference on Computer Communications (INFOCOM)",
        "venueShort": "INFOCOM",
        "venueTag": "INFOCOM '26",
        "year": 2026,
        "kind": "conference",
        "keywords": [
          "Digital Network Twin",
          "Neural Radio Field",
          "Online Learning"
        ]
      },
      {
        "id": "cao2025poster",
        "title": "Poster: Multi-Layer Digital Transportation Twin",
        "authors": [
          "Jiahe Cao",
          "Qiang Liu",
          "Li Zhao",
          "Nathan Huynh"
        ],
        "venue": "2025 IEEE 3rd International Conference on Mobility, Operations, Services and Technologies (MOST)",
        "venueShort": "MOST",
        "venueTag": "MOST '25",
        "year": 2025,
        "kind": "conference",
        "keywords": [
          "Digital Twin",
          "Transportation Systems",
          "Multi-Layer Modeling"
        ]
      }
    ]
  }
];

export const allPublications: Publication[] = [
  {
    "id": "cao2026edgeserving",
    "title": "EdgeServing: Deadline-Aware Multi-DNN Serving at the Edge",
    "authors": [
      "Jiahe Cao",
      "Xiaomeng Li",
      "Qiang Liu",
      "Tao Han",
      "Ning Zhang",
      "Weisong Shi"
    ],
    "venue": "2026 35th International Conference on Computer Communications and Networks (ICCCN)",
    "venueShort": "ICCCN",
    "venueTag": "ICCCN '26",
    "year": 2026,
    "kind": "conference",
    "keywords": [
      "Edge AI",
      "Multi-DNN Serving",
      "Deadline-Aware Scheduling"
    ]
  },
  {
    "id": "zhang2026radtwin",
    "title": "RadTwin: Generalizable Wireless Digital Twin for Dynamic Environments",
    "authors": [
      "Yuru Zhang",
      "Ming Zhao",
      "Qiang Liu",
      "Ahmed Alkhateeb",
      "Abhishek K. Agrawal",
      "Qi Qu"
    ],
    "venue": "2026 35th International Conference on Computer Communications and Networks (ICCCN)",
    "venueShort": "ICCCN",
    "venueTag": "ICCCN '26",
    "year": 2026,
    "kind": "conference",
    "keywords": [
      "Wireless Digital Twin",
      "Generalization",
      "Dynamic Environments"
    ],
    "award": "Best Paper Award"
  },
  {
    "id": "li2026automatic",
    "title": "Automatic Network Planning with Digital Radio Twin",
    "authors": [
      "Xiaomeng Li",
      "Yuru Zhang",
      "Qiang Liu",
      "Mehmet Can Vuran",
      "Nathan Huynh",
      "Li Zhao",
      "Mizan Rahman",
      "Eren Erman Ozguven"
    ],
    "venue": "IEEE International Conference on Communications (ICC)",
    "venueShort": "ICC",
    "venueTag": "ICC '26",
    "year": 2026,
    "kind": "conference",
    "keywords": [
      "Digital Radio Twin",
      "Network Planning",
      "Sim-to-Real"
    ]
  },
  {
    "id": "zhang2026onetwin",
    "title": "oneTwin: Online Digital Network Twin via Neural Radio Radiance Field",
    "authors": [
      "Yuru Zhang",
      "Ming Zhao",
      "Qiang Liu",
      "Nakjung Choi"
    ],
    "venue": "IEEE Conference on Computer Communications (INFOCOM)",
    "venueShort": "INFOCOM",
    "venueTag": "INFOCOM '26",
    "year": 2026,
    "kind": "conference",
    "keywords": [
      "Digital Network Twin",
      "Neural Radio Field",
      "Online Learning"
    ]
  },
  {
    "id": "zhao2026inran",
    "title": "inRAN: Interpretable Online Bayesian Learning for Network Automation in Open Radio Access Networks",
    "authors": [
      "Ming Zhao",
      "Yuru Zhang",
      "Qiang Liu",
      "Ahan Kak",
      "Nakjung Choi"
    ],
    "venue": "IEEE Conference on Computer Communications (INFOCOM)",
    "venueShort": "INFOCOM",
    "venueTag": "INFOCOM '26",
    "year": 2026,
    "kind": "conference",
    "keywords": [
      "O-RAN",
      "Network Automation",
      "Interpretable AI"
    ]
  },
  {
    "id": "cao2025poster",
    "title": "Poster: Multi-Layer Digital Transportation Twin",
    "authors": [
      "Jiahe Cao",
      "Qiang Liu",
      "Li Zhao",
      "Nathan Huynh"
    ],
    "venue": "2025 IEEE 3rd International Conference on Mobility, Operations, Services and Technologies (MOST)",
    "venueShort": "MOST",
    "venueTag": "MOST '25",
    "year": 2025,
    "kind": "conference",
    "keywords": [
      "Digital Twin",
      "Transportation Systems",
      "Multi-Layer Modeling"
    ]
  },
  {
    "id": "zhao2025adaslicing",
    "title": "AdaSlicing: Adaptive Online Network Slicing Under Continual Network Dynamics in Open Radio Access Networks",
    "authors": [
      "Ming Zhao",
      "Yuru Zhang",
      "Qiang Liu",
      "Ahan Kak",
      "Nakjung Choi"
    ],
    "venue": "IEEE Conference on Computer Communications (INFOCOM)",
    "venueShort": "INFOCOM",
    "venueTag": "INFOCOM '25",
    "year": 2025,
    "kind": "conference",
    "keywords": [
      "Network Slicing",
      "Continual Adaptation",
      "Online Learning"
    ]
  },
  {
    "id": "zhao2024lefi",
    "title": "LeFi: Learn to Incentivize Federated Learning in Automotive Edge Computing",
    "authors": [
      "Ming Zhao",
      "Yuru Zhang",
      "Qiang Liu",
      "Tao Han"
    ],
    "venue": "IEEE Global Communications Conference (GLOBECOM)",
    "venueShort": "GLOBECOM",
    "venueTag": "GLOBECOM '24",
    "year": 2024,
    "kind": "conference",
    "keywords": [
      "Federated Learning",
      "Incentive Design",
      "Automotive Edge"
    ]
  },
  {
    "id": "cao2024cave",
    "title": "CAVE: Crowdsourcing Passing-By Vehicles for Reliable In-Vehicle Edge Computing",
    "authors": [
      "Jiahe Cao",
      "Qiang Liu",
      "Dawei Chen",
      "Kyungtae Han"
    ],
    "venue": "IEEE Global Communications Conference (GLOBECOM)",
    "venueShort": "GLOBECOM",
    "venueTag": "GLOBECOM '24",
    "year": 2024,
    "kind": "conference",
    "keywords": [
      "Vehicular Edge Computing",
      "Crowdsourcing",
      "Reliability"
    ]
  },
  {
    "id": "hu2024information",
    "title": "Information Bottleneck-Based Domain Adaptation for Hybrid Deep Learning in Scalable Network Slicing",
    "authors": [
      "Tianlun Hu",
      "Qi Liao",
      "Qiang Liu",
      "Georg Carle"
    ],
    "venue": "IEEE Transactions on Machine Learning in Communications and Networking",
    "venueShort": "TMLCN",
    "venueTag": "TMLCN '24",
    "year": 2024,
    "kind": "journal",
    "keywords": [
      "Network Slicing",
      "Domain Adaptation",
      "Hybrid Deep Learning"
    ]
  },
  {
    "id": "zhang2024crowdsourcing",
    "title": "Crowdsourcing Live High Definition Map via Collaborative Computation in Automotive Edge Computing",
    "authors": [
      "Yuru Zhang",
      "Qiang Liu",
      "Haoxin Wang",
      "Dawei Chen",
      "Kyungtae Han"
    ],
    "venue": "IEEE Transactions on Vehicular Technology",
    "venueShort": "TVT",
    "venueTag": "TVT '24",
    "year": 2024,
    "kind": "journal",
    "keywords": [
      "HD Map",
      "Collaborative Computing",
      "Automotive Edge"
    ]
  },
  {
    "id": "hu2023fast",
    "title": "Fast and Scalable Network Slicing by Integrating Deep Learning with Lagrangian Methods",
    "authors": [
      "Tianlun Hu",
      "Qi Liao",
      "Qiang Liu",
      "Antonio Massaro",
      "Georg Carle"
    ],
    "venue": "IEEE Global Communications Conference (GLOBECOM)",
    "venueShort": "GLOBECOM",
    "venueTag": "GLOBECOM '23",
    "year": 2023,
    "kind": "conference",
    "keywords": [
      "Network Slicing",
      "Deep Learning",
      "Lagrangian Methods"
    ]
  },
  {
    "id": "liu2023adamap",
    "title": "AdaMap: High-Scalable Real-Time Cooperative Perception at the Edge",
    "authors": [
      "Qiang Liu",
      "Yongjie Xue",
      "Yuru Zhang",
      "Dawei Chen",
      "Kyungtae Han"
    ],
    "venue": "IEEE/ACM Symposium on Edge Computing (SEC)",
    "venueShort": "SEC",
    "venueTag": "SEC '23",
    "year": 2023,
    "kind": "conference",
    "keywords": [
      "Cooperative Perception",
      "Edge AI",
      "Resource Orchestration"
    ]
  },
  {
    "id": "zhang2023ronet",
    "title": "RoNet: Toward Robust Neural Assisted Mobile Network Configuration",
    "authors": [
      "Yuru Zhang",
      "Yongjie Xue",
      "Qiang Liu",
      "Nakjung Choi",
      "Tao Han"
    ],
    "venue": "IEEE International Conference on Communications (ICC)",
    "venueShort": "ICC",
    "venueTag": "ICC '23",
    "year": 2023,
    "kind": "conference",
    "keywords": [
      "Network Configuration",
      "Robust Learning",
      "Neural-Assisted Control"
    ]
  },
  {
    "id": "xue2023comap",
    "title": "CoMap: Proactive Provision for Crowdsourcing Map in Automotive Edge Computing",
    "authors": [
      "Yongjie Xue",
      "Yuru Zhang",
      "Qiang Liu",
      "Dawei Chen",
      "Kyungtae Han"
    ],
    "venue": "IEEE International Conference on Communications (ICC)",
    "venueShort": "ICC",
    "venueTag": "ICC '23",
    "year": 2023,
    "kind": "conference",
    "keywords": [
      "Crowdsourcing Map",
      "Proactive Provisioning",
      "Automotive Edge"
    ]
  },
  {
    "id": "hu2023inter",
    "title": "Inter-Cell Network Slicing with Transfer Learning Empowered Multi-Agent Deep Reinforcement Learning",
    "authors": [
      "Tianlun Hu",
      "Qi Liao",
      "Qiang Liu",
      "Georg Carle"
    ],
    "venue": "IEEE Open Journal of the Communications Society",
    "venueShort": "OJ-COMS",
    "venueTag": "OJ-COMS '23",
    "year": 2023,
    "kind": "journal",
    "keywords": [
      "Network Slicing",
      "Transfer Learning",
      "Multi-Agent RL"
    ]
  },
  {
    "id": "liu2022real",
    "title": "Real-Time Dynamic Map with Crowdsourcing Vehicles in Edge Computing",
    "authors": [
      "Qiang Liu",
      "Tao Han",
      "Jiang Linda Xie",
      "BaekGyu Kim"
    ],
    "venue": "IEEE Transactions on Intelligent Vehicles",
    "venueShort": "TIV",
    "venueTag": "TIV '22",
    "year": 2022,
    "kind": "journal",
    "keywords": [
      "Dynamic Map",
      "Crowdsourcing Vehicles",
      "Edge Computing"
    ]
  },
  {
    "id": "liu2022deep",
    "title": "Deep Reinforcement Learning for End-to-End Network Slicing: Challenges and Solutions",
    "authors": [
      "Qiang Liu",
      "Nakjung Choi",
      "Tao Han"
    ],
    "venue": "IEEE Network Magazine",
    "venueShort": "IEEE Network",
    "venueTag": "IEEE Network '22",
    "year": 2022,
    "kind": "journal",
    "keywords": [
      "Network Slicing",
      "Deep RL",
      "End-to-End"
    ]
  },
  {
    "id": "liu2022atlas",
    "title": "Atlas: Automate Online Service Configuration in Network Slicing",
    "authors": [
      "Qiang Liu",
      "Nakjung Choi",
      "Tao Han"
    ],
    "venue": "Proceedings of the 18th International Conference on emerging Networking EXperiments and Technologies (CoNEXT)",
    "venueShort": "CoNEXT",
    "venueTag": "CoNEXT '22",
    "year": 2022,
    "kind": "conference",
    "keywords": [
      "Network Slicing",
      "Service Configuration",
      "Online Learning"
    ]
  },
  {
    "id": "liu2022edgemap",
    "title": "EdgeMap: CrowdSourcing High Definition Map in Automotive Edge Computing",
    "authors": [
      "Qiang Liu",
      "Yuru Zhang",
      "Haoxin Wang"
    ],
    "venue": "IEEE International Conference on Communications (ICC)",
    "venueShort": "ICC",
    "venueTag": "ICC '22",
    "year": 2022,
    "kind": "conference",
    "keywords": [
      "HD Map",
      "Crowdsourcing",
      "Automotive Edge"
    ]
  },
  {
    "id": "hu2022network",
    "title": "Network Slicing via Transfer Learning aided Distributed Deep Reinforcement Learning",
    "authors": [
      "Tianlun Hu",
      "Qi Liao",
      "Qiang Liu",
      "Georg Carle"
    ],
    "venue": "IEEE Global Communications Conference (GLOBECOM)",
    "venueShort": "GLOBECOM",
    "venueTag": "GLOBECOM '22",
    "year": 2022,
    "kind": "conference",
    "keywords": [
      "Network Slicing",
      "Transfer Learning",
      "Distributed RL"
    ]
  },
  {
    "id": "hu2022inter",
    "title": "Inter-cell Slicing Resource Partitioning via Coordinated Multi-Agent Deep Reinforcement Learning",
    "authors": [
      "Tianlun Hu",
      "Qi Liao",
      "Qiang Liu",
      "Dan Wellington",
      "Georg Carle"
    ],
    "venue": "IEEE International Conference on Communications (ICC)",
    "venueShort": "ICC",
    "venueTag": "ICC '22",
    "year": 2022,
    "kind": "conference",
    "keywords": [
      "Network Slicing",
      "Multi-Agent RL",
      "Resource Partitioning"
    ],
    "award": "Best Paper Award"
  },
  {
    "id": "liu2021onslicing",
    "title": "OnSlicing: Online End-to-End Network Slicing with Reinforcement Learning",
    "authors": [
      "Qiang Liu",
      "Nakjung Choi",
      "Tao Han"
    ],
    "venue": "Proceedings of the 17th International Conference on emerging Networking EXperiments and Technologies (CoNEXT)",
    "venueShort": "CoNEXT",
    "venueTag": "CoNEXT '21",
    "year": 2021,
    "kind": "conference",
    "keywords": [
      "Network Slicing",
      "Reinforcement Learning",
      "Safe Online Learning"
    ]
  },
  {
    "id": "liu2021constraint",
    "title": "Constraint-Aware Deep Reinforcement Learning for End-to-End Resource Orchestration in Mobile Networks",
    "authors": [
      "Qiang Liu",
      "Nakjung Choi",
      "Tao Han"
    ],
    "venue": "IEEE 29th International Conference on Network Protocols (ICNP)",
    "venueShort": "ICNP",
    "venueTag": "ICNP '21",
    "year": 2021,
    "kind": "conference",
    "keywords": [
      "Resource Orchestration",
      "Constrained RL",
      "End-to-End Networks"
    ]
  },
  {
    "id": "liu2021livemap",
    "title": "LiveMap: Real-Time Dynamic Map in Automotive Edge Computing",
    "authors": [
      "Qiang Liu",
      "Tao Han",
      "Jiang Linda Xie",
      "BaekGyu Kim"
    ],
    "venue": "IEEE Conference on Computer Communications (INFOCOM)",
    "venueShort": "INFOCOM",
    "venueTag": "INFOCOM '21",
    "year": 2021,
    "kind": "conference",
    "keywords": [
      "Dynamic Map",
      "Real-Time Perception",
      "Automotive Edge"
    ]
  }
];
